//! Integration test validating that .ntc binary files generated by the Python prototype
//! conform strictly to the NtcHeader specification and pass all Rust core validations.

use std::fs::File;
use std::io::Read;
use std::path::{Path, PathBuf};
use vntx_core::{
    compute_texture_hash,
    format::{HEADER_SIZE_BYTES, NTC_MAGIC, NTC_VERSION, WEIGHTS_OFFSET_DEFAULT},
    NtcChannels, NtcHeader, NtcPrecision,
};

fn resolve_fixture_path() -> PathBuf {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".to_string());
    let workspace_fixture =
        Path::new(&manifest_dir).join("../../tests/fixtures/sample_texture.ntc");
    if workspace_fixture.exists() {
        return workspace_fixture;
    }
    PathBuf::from("tests/fixtures/sample_texture.ntc")
}

#[test]
fn test_validate_exported_fixture_if_present() {
    let fixture_path = resolve_fixture_path();
    assert!(
        fixture_path.exists(),
        "Fixture {:?} must exist after running prototype trainer",
        fixture_path
    );

    let mut file = File::open(&fixture_path).expect("Failed to open fixture file");
    let mut buffer = Vec::new();
    file.read_to_end(&mut buffer)
        .expect("Failed to read fixture file");

    assert!(
        buffer.len() >= HEADER_SIZE_BYTES,
        "Fixture must be at least 64 bytes"
    );

    let header = NtcHeader::from_bytes(&buffer[0..HEADER_SIZE_BYTES])
        .expect("Header deserialization and validation must succeed");

    assert_eq!(header.get_magic(), NTC_MAGIC);
    assert_eq!(header.get_version(), NTC_VERSION);
    assert_eq!(header.get_channels(), NtcChannels::Rgba as u8);
    assert_eq!(header.get_precision(), NtcPrecision::Fp16 as u8);
    assert_eq!(header.get_layers_count(), 3);
    assert_eq!(header.get_hidden_dim(), 64);
    assert_eq!(header.get_weights_offset(), WEIGHTS_OFFSET_DEFAULT);

    let expected_weights_size = header
        .calculate_expected_weights_size()
        .expect("Weights calculation");
    assert_eq!(header.get_weights_size(), expected_weights_size);

    let total_file_size = (HEADER_SIZE_BYTES as u64) + header.get_weights_size();
    assert_eq!(
        buffer.len() as u64,
        total_file_size,
        "Total fixture size must equal header size + weights payload"
    );
}

#[test]
fn test_synthetically_constructed_fixture_round_trip() {
    let raw_pixels = vec![128u8; 1024 * 1024 * 4];
    let texture_hash = compute_texture_hash(&raw_pixels);

    let header = NtcHeader::new(
        texture_hash,
        1024,
        1024,
        NtcChannels::Rgba,
        NtcPrecision::Fp16,
        3,
        64,
    )
    .expect("Valid header creation");

    let weights_size = header.get_weights_size() as usize;
    let dummy_weights = vec![0x3Cu8; weights_size]; // 0x3C00 is 1.0 in FP16

    let mut full_file = Vec::with_capacity(HEADER_SIZE_BYTES + weights_size);
    full_file.extend_from_slice(&header.to_bytes());
    full_file.extend_from_slice(&dummy_weights);

    let parsed_header = NtcHeader::from_bytes(&full_file[0..HEADER_SIZE_BYTES])
        .expect("Deserialization of synthetic file header");

    assert_eq!(header, parsed_header);
    assert_eq!(full_file.len(), HEADER_SIZE_BYTES + weights_size);
}
